artifacts_root: artifacts

data_ingestion:
  root_dir: artifact/data_ingestion
  source_URL: https://drive.google.com/file/d/1VPTm1HAhz4GTSQdN9Jb0drQkHSuIS6N6/view?usp=drive_link
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifact/data_ingestion